# Generated by Django 5.0 on 2023-12-25 21:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(blank=True, max_length=50, null=True)),
                ('bidprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('listingid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Closebid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('lister', models.CharField(blank=True, max_length=64, null=True)),
                ('bidder', models.CharField(blank=True, max_length=64, null=True)),
                ('listingid', models.IntegerField()),
                ('finalbid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comment', models.CharField(max_length=30)),
                ('listingid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('finalbid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lister', models.CharField(blank=True, max_length=50, null=True)),
                ('watcher', models.CharField(blank=True, max_length=50, null=True)),
                ('listingid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand', models.CharField(default='', max_length=256, null=True)),
                ('description', models.CharField(default='', max_length=512, null=True)),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='myapp/images')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
