# Generated by Django 5.0 on 2024-01-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='bidemail',
            field=models.EmailField(default='abesit.darshil@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='closebid',
            name='bidmail',
            field=models.EmailField(default='abesit.darshil@gmail.com', max_length=254),
        ),
    ]
