# Generated by Django 5.0 on 2024-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_bidmail_closebid_bidemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='closebid',
            name='brand',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
